apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-docker
  labels:
    app.kubernetes.io/name: {{ include "airflow.name" . }}
    helm.sh/chart: {{ include "airflow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-docker
      port: 2375
      targetPort: tcp-docker
  selector:
    app.kubernetes.io/name: {{ include "airflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: docker
